// Copyright (c) 2026 YouTube Shorter Gemini. All rights reserved.
// Licensed under the Apache-2.0 License. See LICENSE file in the project root for full license information.

import {
  Entity,
  PrimaryGeneratedColumn,
  Column,
  CreateDateColumn,
  UpdateDateColumn,
  Index,
} from 'typeorm';
import { IsNotEmpty, MaxLength } from 'class-validator';

/**
 * Project entity representing a video editing project in the youtube-shorter-gemini system.
 *
 * Each project contains a reference to an uploaded video file and its extracted metadata.
 * Projects are the top-level container for video processing workflows.
 *
 * @entity
 */
@Entity('projects')
export class Project {
  /**
   * Unique identifier for the project (UUID v4)
   */
  @PrimaryGeneratedColumn('uuid')
  id: string;

  /**
   * User-provided project name
   * @example "My Awesome Shorts Project"
   */
  @Column({ type: 'varchar', length: 255 })
  @IsNotEmpty({ message: 'Project name is required' })
  @MaxLength(255, { message: 'Project name cannot exceed 255 characters' })
  name: string;

  /**
   * User has acknowledged that data is processed locally and can be deleted
   * FR-03 compliance
   */
  @Column({ type: 'boolean', default: false })
  deletionPolicyAcknowledged: boolean;

  /**
   * Full video transcript (SRT format)
   * Generated by Gemini Audio Analysis
   */
  @Column({ type: 'text', nullable: true })
  transcript?: string;

  /**
   * User consent for sharing anonymized data for AI learning
   * FR-13 compliance
   */
  @Column({ type: 'boolean', default: false })
  aiLearningConsent: boolean;

  /**
   * Project has been exported to a final video
   */
  @Column({ type: 'boolean', default: false })
  isExported: boolean;

  /**
   * Path to the video file
   *
   * For desktop local use case (Story 1.1): References user's original file path
   * For future YouTube downloads (Epic 2+): Will store temporary download path
   *
   * @example "/Users/john/Videos/my-video.mp4" (desktop)
   * @example "/tmp/youtube-shorter/downloads/abc123/video.mp4" (future)
   */
  @Column({ type: 'varchar', length: 500 })
  videoPath: string;

  /**
   * Video duration in seconds (extracted by FFmpeg)
   * @example 125.5
   */
  @Column({ type: 'float', nullable: true })
  duration?: number;

  /**
   * Video framerate (e.g. 24, 25, 29.97, 30, 60)
   */
  @Column({ type: 'float', nullable: true })
  framerate?: number;

  /**
   * Video resolution (width x height)
   * @example "1920x1080"
   */
  @Column({ type: 'varchar', length: 50, nullable: true })
  resolution?: string;

  /**
   * Video codec name
   * @example "h264"
   */
  @Column({ type: 'varchar', length: 50, nullable: true })
  codec?: string;

  /**
   * Timestamp when the project was created
   * Indexed for efficient cleanup queries
   */
  @Index()
  @CreateDateColumn()
  createdAt: Date;

  /**
   * Custom analysis prompt override for this project
   */
  @Column({ type: 'text', nullable: true })
  customPrompt?: string;

  /**
   * Minimum duration in seconds of generated shorts
   */
  @Column({ type: 'integer', nullable: true })
  minDuration?: number;

  /**
   * Maximum duration in seconds of generated shorts
   */
  @Column({ type: 'integer', nullable: true })
  maxDuration?: number;

  /**
   * Timestamp when the project was last updated
   */
  @UpdateDateColumn()
  updatedAt: Date;
}
